### ISSUE TITLE
[Feature Request]: Controls and Recipes

### ISSUE THREAD

**Issue by sleeplessKomodo** [LarsMans64/InfinityButtons#36]
### Feature Request

Can you please add recipes to the readme? I had to install a mod to figure this out, which seems unnecessary, 

Also, how do you use the buttons? I ask for controls because I placed a normal stone button next to an iron door, which could be pressed to open the door, without issue. However, other buttons like iron or gold buttons don't seem to work. Is there a configurable control or a default key to use the buttons? Right-mouse-button doesn't seem to do anything, so I can't tell if I'm doing something wrong, or if it's a bug?

### What version of the mod is this request for?

Fabric

**Comment by curryducker** [comment]
We can't list recipes and functions for every item. That's why we have in-game item descriptions to tell the player what a button does (in the case of iron and gold buttons, they are only pressed by projectiles). For the recipe's i always recommend having JEI or EMI installed, if you really don't want that you can always use the vanilla recipe book.

**Comment by sleeplessKomodo** [comment]
> We can't list recipes and functions for every item. That's why we have in-game item descriptions to tell the player what a button does (in the case of iron and gold buttons, they are only pressed by projectiles). For the recipe's i always recommend having JEI or EMI installed, if you really don't want that you can always use the vanilla recipe book.

Thanks, I didn't want to create a new issue, but this answers the question, sorry for the bother!
